#!/bin/bash

# Organo - New Repository Setup Script
# This script helps you create a new GitHub repository for your modern React app

echo "🎉 Welcome to Organo - Modern React App Setup!"
echo "=============================================="
echo ""
echo "Your project is ready with:"
echo "✅ Vite 6 - Lightning-fast build tool"
echo "✅ React 19 - Latest React features"
echo "✅ Vitest - Modern testing framework (95%+ coverage)"
echo "✅ ESLint 9 - Code quality"
echo "✅ Prettier - Code formatting"
echo "✅ Husky - Git hooks for quality control"
echo ""
echo "📋 To create a new GitHub repository:"
echo ""
echo "1. Go to https://github.com/new"
echo "2. Repository name: organo-modern (or your preferred name)"
echo "3. Description: 'A modern React application built with Vite, featuring automated testing, code quality tools, and best practices'"
echo "4. Make it Public (recommended for portfolio projects)"
echo "5. ⚠️  IMPORTANT: Leave all checkboxes UNCHECKED (no README, .gitignore, or license)"
echo "6. Click 'Create repository'"
echo ""
echo "7. Copy the repository URL from the setup page"
echo "8. Run these commands:"
echo ""
echo "   git remote add origin <your-repo-url>"
echo "   git push -u origin main"
echo ""
echo "🔧 Your git hooks will automatically:"
echo "   - Check code quality before commits"
echo "   - Validate conventional commit messages"
echo "   - Run tests and check coverage before pushes"
echo "   - Ensure builds work before deployment"
echo ""
echo "📚 Available commands:"
echo "   pnpm dev          # Start development server"
echo "   pnpm test         # Run tests"
echo "   pnpm build        # Build for production"
echo "   pnpm test:ui      # Open test UI"
echo "   pnpm lint         # Check code quality"
echo "   pnpm format       # Format code"
echo ""
echo "🎯 Minimum test coverage: 90%"
echo "📝 Commit format: feat/fix/docs/style/refactor/test/chore"
echo ""
echo "Happy coding! 🚀"
